name: Deploy Node.js app to Azure Web App - BuoyProjectBackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: |
          npm install

      - name: Zip the application files
        run: |
          zip -r app.zip server.js package.json package-lock.json

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4045CED7EFB14B0E8E06FCB92B29B4A3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0B95CA57B24B4C2AADE3DD32D8451231 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_90515D4EBE254C6B944783B7956C466E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BuoyProjectBackend'
          slot-name: 'Production'
          package: app.zip
s